sudo: required

language: node_js

services:
  - docker
  - mongodb

before_script:
  - sleep 15
  - cp config/test.json.example config/text.json
  - mongo --eval 'use forumDb; db.createUser({user:"forumUser", pwd:"forumPass", roles:["readWrite"]});'

before_install:
  - docker build -t bcgov/ocwa .

script:
  - npm install
  - npm test
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin


on:
  branch: master