#!/bin/bash

#make sure in the right directory
cd /home/travis/build/bcgov/OCWA/microservices/forumApi


echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
echo "logged in, building now";
printf "\nENV GITHASH $TRAVIS_COMMIT\n" >> Dockerfile
cat Dockerfile

if [ $TRAVIS_BRANCH == "master" ]; then
    docker build -t bcgovimages/ocwa_forum_api:latest -t bcgovimages/ocwa_forum_api:$TRAVIS_COMMIT .
    echo "dockerfile built pushing now";
    docker push bcgovimages/ocwa_forum_api:latest
    docker push bcgovimages/ocwa_forum_api:$TRAVIS_COMMIT
    echo "latest and $TRAVIS_COMMIT pushed successfully";
fi

if [ $TRAVIS_BRANCH == "develop" ]; then
    docker build -t bcgovimages/ocwa_forum_api:edge .;
    echo "dockerfile built pushing now";
    docker push bcgovimages/ocwa_forum_api:edge;
    echo "edge (develop) pushed successfully";
fi

if [ $TRAVIS_BRANCH == $TRAVIS_TAG ]; then
    #Tag build
    docker build -t bcgovimages/ocwa_forum_api:$TRAVIS_TAG .;
    echo "dockerfile built pushing now";
    docker push bcgovimages/ocwa_forum_api:$TRAVIS_TAG;
    echo "$TRAVIS_TAG pushed successfully";
fi