#!/bin/bash

#make sure in the right directory
cd /home/travis/build/bcgov/OCWA/microservices/validateApi

QUAYIO_REPO=$1

echo "$QUAYIO_PASSWORD" | docker login -u "$QUAYIO_USERNAME" --password-stdin quay.io
echo "logged in to quay, building now";
docker build -t quay.io/ikethecoder/$QUAYIO_REPO .
echo "dockerfile built pushing now";
docker push quay.io/ikethecoder/$QUAYIO_REPO
echo "push to quay done successfully";