#!/bin/bash

#make sure in the right directory
cd /home/travis/build/bcgov/OCWA/frontend


echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
echo "logged in, building now";
printf "\nENV GITHASH $TRAVIS_COMMIT\n" >> Dockerfile

if [ $TRAVIS_BRANCH == "master" ]; then
    docker build -t bcgovimages/ocwa_frontend:latest -t bcgovimages/ocwa_frontend:$TRAVIS_COMMIT .;
    echo "dockerfile built pushing now";
    docker push bcgovimages/ocwa_frontend:latest;
    docker push bcgovimages/ocwa_frontend:$TRAVIS_COMMIT;
    echo "latest and $TRAVIS_COMMIT pushed successfully";
fi

if [ $TRAVIS_BRANCH == "develop" ]; then
    docker build -t bcgovimages/ocwa_frontend:edge .;
    echo "dockerfile built pushing now";
    docker push bcgovimages/ocwa_frontend:edge;
    echo "edge (develop) pushed successfully";
fi

if [ "$TRAVIS_BRANCH" == "$TRAVIS_TAG" ]; then
    #Tag build
    docker build -t bcgovimages/ocwa_frontend:$TRAVIS_TAG .;
    echo "dockerfile built pushing now";
    docker push bcgovimages/ocwa_frontend:$TRAVIS_TAG;
    echo "$TRAVIS_TAG pushed successfully";
fi