# Default values for ocwaPolicyApi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: bcgovimages/ocwa_policy_api
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - chart-example.local
  tls: []

##Configuration for OCWA Policy Api
apiPort: 3004
logLevel: error
database:
  host: ocwa-forum-api-mongo.ocwa
  port: 27017
  username: forumApi
  password: password
  dbName: forumApi

apiSecret: "ssh this is a secret"
user:
  idField: Email

createDatabase: false


resources: {}
  # If you want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
