apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "ocwaFrontend.fullname" . }}
  labels:
    app: {{ template "ocwaFrontend.name" . }}
    chart: {{ template "ocwaFrontend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "ocwaFrontend.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ocwaFrontend.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              value: "{{ .Values.port }}"
            - name: HOST
              value: {{ .Values.host }}
            - name: JWT
              value: {{ .Values.jwt }}
            - name: JWT_SECRET
              value: {{ .Values.user.jwtSecret }}
            - name: USER_ID_FIELD
              value: {{ .Values.user.idField }}
          ports:
            - name: http
              containerPort: {{ .Values.apiPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/api-docs
              port: http
          readinessProbe:
            httpGet:
              path: /v1/api-docs
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}