apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ocwaFrontend.fullname" . }}
  labels:
    app: {{ template "ocwaFrontend.name" . }}
    chart: {{ template "ocwaFrontend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "ocwaFrontend.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ocwaFrontend.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              value: "{{ .Values.port }}"
            - name: HOST
              value: {{ .Values.host }}
            - name: AUTH_CALLBACK_URL
              value: "{{ .Values.auth.callbackURL }}"
            - name: FORUM_API_HOST
              value: "{{ .Values.forumApiHost }}"
            - name: FORUM_SOCKET_HOST
              value: "{{ .Values.forumSocket }}"
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "ocwaFrontend.fullname" . }}-secrets
                  key: cookieSecret
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "ocwaFrontend.fullname" . }}-secrets
                  key: jwtSecret
            - name: USER_ID_FIELD
              value: {{ .Values.user.idField }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 150
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 150
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
