apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ocwaFrontend.fullname" . }}-secrets
  labels:
    app: {{ template "ocwaFrontend.name" . }}
    chart: {{ template "ocwaFrontend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  clientSecret: {{ .Values.auth.clientSecret | b64enc }}
  jwtSecret: {{ .Values.global.jwtSecret | b64enc }}
  cookieSecret: {{ .Values.cookieSecret | b64enc }}