apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ocwaFrontend.fullname" . }}-secrets
  labels:
    app: {{ template "ocwaFrontend.name" . }}
    chart: {{ template "ocwaFrontend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  jwtSecret: {{ .Values.jwtSecret | b64enc }}