{{- if .Values.tls.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls
  labels:
    app: {{ template "ocwaFrontend.name" . }}
    chart: {{ template "ocwaFrontend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.crt | b64enc }}
  tls.key: {{ .Values.tls.key | b64enc }}
{{- end }}
