#!/bin/bash

#make sure in the right directory
cd /home/travis/build/bcgov/OCWA/microservices/policyApi


echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
echo "logged in, building now";
docker build -t bcgovimages/ocwa_policy_api:latest -t bcgovimages/ocwa_policy_api:$TRAVIS_COMMIT . .
echo "dockerfile built pushing now";
docker push bcgovimages/ocwa_policy_api:latest
docker push bcgovimages/ocwa_policy_api:$TRAVIS_COMMIT
echo "push done successfully";

#!/bin/bash

#make sure in the right directory
cd /home/travis/build/bcgov/OCWA/microservices/forumApi


echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
echo "logged in, building now";
docker build -t bcgovimages/ocwa_forum_api:latest -t bcgovimages/ocwa_forum_api:$TRAVIS_COMMIT .
echo "dockerfile built pushing now";
docker push bcgovimages/ocwa_forum_api:latest
docker push bcgovimages/ocwa_forum_api:$TRAVIS_COMMIT
echo "push done successfully";
