apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ocwaProjectApi.fullname" . }}-secrets
  labels:
    app: {{ template "ocwaProjectApi.name" . }}
    chart: {{ template "ocwaProjectApi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  dbPassword: {{ .Values.database.password | b64enc }}
  jwtSecret: {{ .Values.global.jwtSecret | b64enc }}
  apiKey: {{ .Values.apiKey | b64enc }}
