{{ if .Values.emailTemplateEnabled }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ocwaForumApi.fullname" . }}-forumapi-configmap
data:
  emailTemplate.html: |-
{{ .Values.emailTemplate | indent 4}}

{{- end}}
