global.confirm = jest.fn(() => true);
global.FILES_API_HOST = 'http://localhost:3000';
global.SOCKET_HOST = 'ws://localhost:3000';
global.REQUEST_SOCKET_HOST = 'ws://localhost:2998';
global.COMMIT = '98sf9842rse8238ew9r8we9f89';
global.HELP_URL = 'http://example.com/help';
global.ID_FIELD = 'preferred_username';
global.EXPORTER_GROUP = '/exporter';
global.OC_GROUP = '/oc';
global.EXPORTER_MODE = 'export';
global.CODE_EXPORT_ENABLED = true;
global.DATA_REQUEST_FORM = 'data-export';
global.CODE_REQUEST_FORM = 'code-export';
global.REPORTS_GROUP = '/reports';
global.REPOSITORY_HOST = 'https://example.com/shares/';
global.ZONE = 'internal';
global.VERSION = '1.1.1';
