#!/bin/bash

#make sure in the right directory
cd /home/travis/build/bcgov/OCWA/microservices/validateApi


echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
echo "logged in, building now";
echo "ENV GITHASH $TRAVIS_COMMIT" >> Dockerfile

if [ $TRAVIS_BRANCH == "master" ]; then
    docker build -t bcgovimages/ocwa_validate_api:latest -t bcgovimages/ocwa_validate_api:$TRAVIS_COMMIT .
    echo "dockerfile built pushing now";
    docker push bcgovimages/ocwa_validate_api:latest
    docker push bcgovimages/ocwa_validate_api:$TRAVIS_COMMIT
    echo "latest and $TRAVIS_COMMIT pushed successfully";
fi

if [ $TRAVIS_BRANCH == "develop" ]; then
    docker build -t bcgovimages/ocwa_validate_api:edge .;
    echo "dockerfile built pushing now";
    docker push bcgovimages/ocwa_validate_api:edge;
    echo "edge (develop) pushed successfully";
fi