{{- if .Values.createDatabase -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ocwaPolicyApi.fullname" . }}-mongo
  labels:
    app: {{ template "ocwaPolicyApi.name" . }}-mongo
    chart: {{ template "ocwaPolicyApi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: mongo
      protocol: TCP
      name: mongo
  selector:
    app: {{ template "ocwaPolicyApi.name" . }}-mongo
    release: {{ .Release.Name }}
{{- end }}