<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_gfggggg</name>
   <tag></tag>
   <elementGuidId>8030b58a-35da-4934-a959-42f86e9e595f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div/main/div[2]/div/div/div[2]/div/div/div/div/div/table/tbody/tr/td[2]/strong/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/requests/5c08241fe35b430013db0cae</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>gfggggg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[@class=&quot;LayerManager__AppWrapper-ues105-0 oCRpv&quot;]/main[@class=&quot;src-modules-app-components-app-styles_main--HUjPm6n8&quot;]/div[@class=&quot;src-modules-app-components-app-styles_container--Gaae__yt&quot;]/div[@class=&quot;sc-dnqmqq hYEhCn&quot;]/div[@class=&quot;sc-iwsKbI kTSErh&quot;]/div[@class=&quot;sc-jTzLTM gBDbcZ&quot;]/div[@class=&quot;sc-fjdhpX dBNkfU&quot;]/div[@class=&quot;sc-jzJRlG epCAxu&quot;]/div[1]/div[1]/div[@class=&quot;LoadingContainerAdvanced__Container-sc-1s2zdt8-0 cFyKDm&quot;]/table[@class=&quot;DynamicTable__Table-sc-1naczgt-0 cFUPVR&quot;]/tbody[1]/tr[@class=&quot;TableRow__TableBodyRow-sc-1kwbh2h-0 jLQmXi&quot;]/td[@class=&quot;TableCell__TableBodyCell-sc-1mgclzx-0 dGStZT&quot;]/strong[1]/a[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='main']/div/div/main/div[2]/div/div/div[2]/div/div/div/div/div/table/tbody/tr/td[2]/strong/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <value>//a[contains(text(),'gfggggg')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Output Checker'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Updated On'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dec 5th, 2018'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dec 5th, 2018'])[2]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <value>//a[contains(@href, '/requests/5c08241fe35b430013db0cae')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//strong/a</value>
   </webElementXpaths>
</WebElementEntity>
