<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_All</name>
   <tag></tag>
   <elementGuidId>e46b1338-cfb4-4490-afcb-c261879f15a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div/main/div[2]/div/div/div[2]/header/div/div/div/nav/div/div/button/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[@class=&quot;LayerManager__AppWrapper-ues105-0 oCRpv&quot;]/main[@class=&quot;src-modules-app-components-app-styles_main--HUjPm6n8&quot;]/div[@class=&quot;src-modules-app-components-app-styles_container--Gaae__yt&quot;]/div[@class=&quot;sc-dnqmqq hYEhCn&quot;]/div[@class=&quot;sc-iwsKbI kTSErh&quot;]/div[@class=&quot;sc-jTzLTM gBDbcZ&quot;]/header[@class=&quot;src-modules-requests-components-requests-list-styles_header--1ErTpvDv&quot;]/div[@class=&quot;sc-fjdhpX dBNkfU&quot;]/div[@class=&quot;sc-jzJRlG epCAxu&quot;]/div[1]/nav[@class=&quot;src-modules-requests-components-requests-list-styles_filters--2zXt4B4j&quot;]/div[@class=&quot;sc-gzVnrw dlVKOv&quot;]/div[@class=&quot;sc-htoDjs etChcU&quot;]/button[@class=&quot;sc-ifAKCX kcQtWv&quot;]/span[1]/span[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='main']/div/div/main/div[2]/div/div/div[2]/header/div/div/div/nav/div/div/button/span/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Requests'])[1]/following::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Request'])[1]/following::span[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft'])[1]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Queued/In Review'])[1]/preceding::span[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//nav/div/div/button/span/span</value>
   </webElementXpaths>
</WebElementEntity>
