{{ if or (.Values.emailTemplateEnabled) (.Values.emailSubmitTemplateEnabled) }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ocwaRequestApi.fullname" . }}-requestapi-configmap
data:
  emailTemplate.html: |-
{{ .Values.emailTemplate | indent 4}}

  emailSubmitTemplate.html: |-
{{ .Values.emailSubmitTemplate | indent 4}}

{{- end}}
