apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ocwaValidateApi.fullname" . }}-secrets
  labels:
    app: {{ template "ocwaValidateApi.name" . }}
    chart: {{ template "ocwaValidateApi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  dbPassword: {{ .Values.database.password | b64enc }}
  storageKey: {{ .Values.storage.key | b64enc }}
  storageSecret: {{ .Values.storage.secret | b64enc }}
  apiSecret: {{ .Values.apiSecret | b64enc }}
