# Default values for ocwaFrontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: bcgovimages/ocwa_frontend
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - chart-example.local
  tls: []

##Configuration for OCWA Policy Api
port: 8000
logLevel: error

host: "serverHostedOnHere"

cookieSecret: "COOKIE_SECRET_HERE"
jwtSecret: "ssh this is a secret"
forumApiHost: "ocwa-forum-api.ocwa"
forumSocket: "ocwa-forum-api.ocwa:3001"
auth:
  authorizationEndpoint: "openid.auth.endpoint"
  callbackURL: "chart-example.local/auth"
  clientID: "outputchecker"
  clientSecret: "ssh this is a secret"
  issuer: "openid.auth.issuer"
  scope: "openid offline_access"
  tokenEndpoint: "openid.auth.tokenEndpoint"
  userInfoURL: "openid.userinfo.url"
user:
  idField: Email


resources: {}
  # If you want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
